config/routes.rb
Rails.application.routes.draw do

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :books do
    collection do
      get :success
    end
  end
  resources :users
  resources :categories
  resources :circulates do
    collection do
      get :tongji
      get :usersTongji
    end
  end
  resources :tags
  resources :sessions
  resources :mains

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: "books#index"

  namespace :interface do
    resources :books, :only =>[] do
      collection do
        get :all
      end
    end
  end

  namespace :interface do
    resources :users, :only =>[] do
      collection do
        get :all
      end
    end
  end
end

app/models/book.rb
class Book <ActiveRecord::Base
  belongs_to :category
  has_many :bookTags
  has_many :tags, :through=>:bookTags
  has_many :circulates
end

app/controllers/books_controller.rb
class BooksController <ApplicationController

  before_action :find_book_by_id, :only=>[:edit, :update, :destroy, :show]
  before_filter :authorize, :except=>[:index, :show]

  def index
    @books = Book.all.page(params[:page]).per(10)
    @books = @books.where("name like '%#{params[:book_name]}%'") if params[:book_name].present?
    @books = @books.where("author like '%#{params[:book_author]}%'") if params[:book_author].present?
    @books = @books.joins(:category).where("categories.name like ? ", "%#{params[:book_category]}%") if params[:book_category].present?
    @books = @books.joins(:tags).where("tags.name like ? ", "%#{params[:book_tag]}%") if params[:book_tag].present?
  end

  def new
    authorize! :create, :message=>"没有权限"
    @book = Book.new
  end

  def create
    @book = Book.create book_params
    #  :name=>params[:book][:name],
    #  :author=>params[:book][:author],
    #  :summary=>params[:book][:summary],
       #:category_id=>params[:category_id]
    #  :status_id=>params[:status_id],
    #  :amount=>params[:book][:amount],
    #  :book_position=>params[:book][:book_position],
    #  :tag_group_ids => params[:book][:tag_group_ids]

    #book_id = @book.id
    #params[:tag_group_id].each do |tag_id|
    #  @book.bookTags.create(:tag_id=>tag_id, :book_id=>book_id)
    #end
    redirect_to books_path
  end

  def edit
    authorize! :update, :message=>"没有权限"
  end

  def update
    @book.update book_params
    #@book.name = params[:book][:name]
    #@book.author = params[:book][:author]
    #@book.summary = params[:book][:summary]
    #@book.category_id = params[:category_id]
    #@book.status_id = params[:status_id]
    #@book.amount = params[:book][:amount]
    #@book.book_position = params[:book][:book_position]
    #@book.save
    redirect_to books_path
  end

  def destroy
    authorize! :destroy, :message=>"没有权限"
    @book.delete
    redirect_to books_path
  end

  def show
    @count = Circulate.joins(:book).where("books.id=?", "#{params[:id]}").where("circulates.status_id=?", "1").count
  end

  def find_book_by_id
    @book = Book.find(params[:id])
  end

private
  def book_params
    params.require(:book).permit!
  end
end

app/controllers/interface/books_controller.rb
class Interface::BooksController <ActionController::Base
  def all
    all_books = Book.all.map do |book|
      {
        :id=>book.id,
        :name=>book.name,
        :author=>book.author,
        :book_position=>book.book_position,
        :tag_ids=>book.tag_ids
      }
    end
    render :json=>{
      :success => true,
      :result => all_books
    }
  end
end

app/views/books/_form.html.erb
<style>
input.error{border:1px solid red}
textarea.error{border:1px solid red}
label.error {
  font-weight: bold;
  color: #EA5200;
  float: right;
  margin-right: 46%;
}
</style>
<script>
$(function(){
  $("#form").validate({
    rules:{
      "book[name]":"required",
      "book[author]":"required",
      "book[summary]":"required",
      "book[tag_ids][]":"required",
      "book[status_id]":"required",
      "book[amount]":{
        "required":true,
        "digits":true,
        "min":1
      },
      "book[book_position]":"required",
    },
    messages:{
      "book[name]":"图书名称不能为空",
      "book[author]":"图书作者不能为空",
      "book[summary]":"图书简介不能为空",
      "book[tag_ids][]":"图书标签不能为空",
      "book[status_id]":"图书是否可以外借必填",
      "book[amount]":{
         "required":"图书总量不能为空",
         "digits":"必须输入正整数",
         "min":"必须大于1"
      },
      "book[book_position]":"图书位置不能为空",
    }
  });
});
</script>
<%= form_for @book, :html=>{:id=>"form"} do |f| %>
  <div class="input-group">
    <span class="input-group-addon">图书名称</span>
    <%= f.text_field :name, :class=>"form-control", :style=>"width:40%" %>
  </div>
  <br/>
  <div class="input-group">
    <span class="input-group-addon">图书作者</span>
    <%= f.text_field :author, :class=>"form-control", :style=>"width:40%" %>
  </div>
  <br/>
  <div class="input-group">
    <span class="input-group-addon">图书简介</span>
    <%= f.text_area :summary, :size=>"50*12" %>
  </div>
  <br/>
  <div class="input-group">
    <span class="input-group-addon">图书分类</span>
    <%= f.select :category_id, options_from_collection_for_select(Category.all,'id','name', @book.category_id)%>
  </div>
  <br>
  <div class="input-group">
    <span class="input-group-addon">图书标签</span>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
    <%# Tag.all.each do |tag|%>
      <%#= check_box_tag 'tag_group_id[]', tag.id, @book.bookTags.map(&:tag_id).include?(tag.id) %>
      <%#= label_tag tag.name %>
    <%#end%>
  </div>
  <br/>
  <div class="input-group">
    <span class="input-group-addon">图书是否可外借</span>
    <% if @book.status_id == nil %>
      <%= f.radio_button :status_id, "0" %>
      <%= label_tag "不可借"%>
      <%= f.radio_button :status_id, "1" %>
      <%= label_tag "可借" %>
    <%elsif @book.status_id == 0 %>
      <%= f.radio_button :status_id, "0", checked:true %>
      <%= label_tag "不可借"%>
      <%= f.radio_button :status_id, "1" %>
      <%= label_tag "可借" %>
    <%else%>
      <%= f.radio_button :status_id, "0" %>
      <%= label_tag "不可借"%>
      <%= f.radio_button :status_id, "1", checked:true %>
      <%= label_tag "可借" %>
    <%end%>
  </div>
  <br/>
  <div class="input-group">
    <span class="input-group-addon">图书总量</span>
    <%= f.text_field :amount, :class=>"form-control", :style=>"width:40%" %>
  </div>
  <br/>
  <div class="input-group">
    <span class="input-group-addon">图书位置</span>
    <%= f.text_field :book_position, :class=>"form-control", :style=>"width:40%" %>
  </div>
  <br/>
  <%= f.submit "确定", :class=>"btn btn-primary" %>
  <%= link_to "返回", books_path, :class=>"btn btn-primary" %>
<%end%>

app/views/books/edit.html.erb
<div class="container">
  <h1>图书修改</h1>
  <%= render :partial=>"form" %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div style="margin-top:2%; margin-left:42%">
    <div id="user_header">
      <% if current_user %>
        欢迎<%= current_user.name %>登陆！
      <%= link_to "退出", logout_path %>
    <% else %>
        <%= link_to "注册", signup_path, :class=>"btn btn-primary" %>
      <%= link_to "登陆", login_path, :class=>"btn btn-primary" %>
    <% end %>
    </div>
  </div>
  <h1>图书列表</h1>
  <form method="get" class="form-inline">
    <div class="form-group">
      <div style="width:50%; float:left; margin-top:1%">请输入图书名称：
        <input class="form-control" style="width:50%" type="text" name="book_name" id="book_name" placeholder="模糊匹配全文，例如：ruby详解"/>
      </div>
      <div style="width:50%; float:left; margin-top:1%">请输入图书分类：
        <input class="form-control" style="width:50%" type="text" name="book_category" id="book_category" placeholder="模糊匹配全文，例如：计算机"/>
      </div>
      <div style="width:50%; float:left; margin-top:1%">请输入图书标签：
        <input class="form-control" style="width:50%" type="text" name="book_tag" id="book_tag" placeholder="模糊匹配全文，例如：ruby，java"/>
      </div>
      <div style="width:50%; float:left; margin-top:1%">请输入作者姓名：
        <input class="form-control" style="width:50%" type="text" name="book_author" id="book_author" placeholder="模糊匹配全文，例如：小王"/>
      </div>
      <div style="float:right; margin-right:10%; margin-top:1% ">
        <input type="submit" value="查询" class="btn btn-primary" />
      </div>
    </div>
  </form>
  <br/>
  <table class="table table-striped table-hover">
    <tr>
      <th>图书名称</th>
      <th>图书作者</th>
      <th>图书分类</th>
      <th>图书标签</th>
      <% if current_user == nil %>
      <%elsif  current_user.role == "admin"%>
        <th>操作</th>
      <%else%>
      <%end%>
    </tr>
    <% @books.each do |book| %>
      <tr>
      <td><%= link_to book.name, book_path(:id=>book.id) %></td>
      <td><%= book.author%></td>
      <td><%= book.category.name %></td>
      <td>
        <% book.tags.each do |tag| %>
          <%= tag.name%>
        <%end%>
      </td>
      <% if current_user == nil %>
      <%elsif  current_user.role == "admin"%>
        <td>
          <%= link_to "修改", edit_book_path(:id=>book.id), :class=>"btn btn-primary" %>
          <%= link_to "删除", book_path(:id=>book.id), :method=>"delete", :data=>{:confirm=>"确认要删除吗？"}, :class=>"btn btn-danger" %>
        </td>
      <%else%>
      <%end%>
    </tr>
  <%end%>
  </table>
  <div class="table-actions-bottom" style="float:right">
    <%= paginate @books %>
  </div>
  <% if current_user == nil %>
  <%elsif  current_user.role == "admin"%>
    <%= link_to "新增", new_book_path, :class=>"btn btn-primary" %>
    <%= link_to "返回首页", mains_path, :class=>"btn btn-primary" %>
  <%else%>
  <%end%>
</div>

app/views/books/new.html.erb
<div class="container">
  <h1>图书新增</h1>
  <%= render :partial=>"form" %>
</div>

app/views/books/show.html.erb
<style>
  div{
    font-size:1em;
    margin-left:5%;
  }
</style>

<div class="container">
  <h1>图书详情展示页</h1>
  <div>图书名称：<%= @book.name %></div><br/>
  <div>图书作者：<%= @book.author %></div><br/>
  <div>图书分类：<%= @book.category.name %></div><br/>
  <div>
    图书标签：
    <% @book.tags.each do |tag| %>
    <%= tag.name%>、
    <%end%>
  </div><br/>
  <div>图书简介：<%= @book.summary %></div><br/>
  <div>图书位置：<%= @book.book_position %></div><br/>
  <!--
  <div>
    是否可借：
    <%if @book.status_id==0 %>不可借
    <%else%>可借
    <%end%>
  </div><br/>
  -->
  <% if current_user == nil %>
    <%= link_to "借阅", new_circulate_path(:book_id=>@book.id), :class=>"btn btn-primary" %>
  <% elsif current_user.role == "admin" %>
    <p style="color:red">您是管理员</p>
  <% elsif @book.status_id==0 %>
    <p style="color:red"> 该书目前正在维护中，不可借阅</p>
  <%elsif @book.amount - @count == 0%>
    <p style="color:red"> 该书剩余量为0，请稍后再借</p>
  <%else%>
    <%= link_to "借阅", new_circulate_path(:book_id=>@book.id), :class=>"btn btn-primary" %>
  <%end%>
  <%= link_to "返回", books_path, :class=>"btn btn-primary" %>
</div>

app/views/books/success.html.erb
<div class="container">
  <p style="font-size:3em", align="center">恭喜您，借书成功！！</p>
  <%= link_to "返回", books_path, :class=>"btn btn-primary"%>
</div>