config/routes.rb
Rails.application.routes.draw do

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :books do
    collection do
      get :success
    end
  end
  resources :users
  resources :categories
  resources :circulates do
    collection do
      get :tongji
      get :usersTongji
    end
  end
  resources :tags
  resources :sessions
  resources :mains

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: "books#index"

  namespace :interface do
    resources :books, :only =>[] do
      collection do
        get :all
      end
    end
  end

  namespace :interface do
    resources :users, :only =>[] do
      collection do
        get :all
      end
    end
  end
end

app/models/tag.rb
class Tag <ActiveRecord::Base
  has_many :bookTags
  has_many :books, :through=>:bookTags
end

app/controllers/tags_controller.rb
class TagsController <ApplicationController

  before_action :find_tag_by_id, :only=>[:edit, :update, :destroy]
  before_filter :authorize

  def index
    authorize! :read, :message=>"没有权限"
    @tags = Tag.all.page(params[:page]).per(10)
  end

  def new
    authorize! :create, :message=>"没有权限"
    @tag = Tag.new
  end

  def create
    Tag.create :name=>params[:tag][:name]
    redirect_to tags_path
  end

  def edit
    authorize! :update, :message=>"没有权限"
  end

  def update
    @tag.name = params[:tag][:name]
    @tag.save
    redirect_to tags_path
  end

  def destroy
    authorize! :destroy, :message=>"没有权限"
    @tag.delete
    redirect_to tags_path
  end

  def find_tag_by_id
    @tag = Tag.find(params[:id])
  end

end

app/views/tags/_form.html.erb
<%= form_for @tag, :html=>{:id=>"form"} do |f| %>
  <div class="input-group">
    <span class="input-group-addon">请输入标签名称：</span>
    <%= f.text_field :name, :class=>"form-control", :style=>"width:40%" %>
  </div>
  <br/>
  <%= f.submit "确定", :class=>"btn btn-primary" %>
  <%= link_to "返回", tags_path, :class=>"btn btn-primary" %>
<%end%>

app/views/tags/edit.html.erb
<div class="container">
  <h1>图书标签修改</h1>
  <%= render :partial=>"form" %> 
</div>

app/views/tags/index.html.erb
<div class="container">
  <h1>图书标签列表</h1>
  <table class="table table-striped table-hover">
    <tr>
      <th>图书标签名称</th>
      <th>操作</th>
    </tr>
    <% @tags.each do |tag| %>
      <tr>
      <td><%= tag.name %></td>
      <td>
      <%= link_to "修改", edit_tag_path(:id=>tag.id), :class=>"btn btn-primary" %>
      <%= link_to "删除", tag_path(:id=>tag.id), :method=>"delete", :data=>{:confirm=>"确定要删除这个标签吗？"}, :class=>"btn btn-danger" %>
      </td>
      </tr>
    <%end%>
  </table>
  <div class="table-actions-bottom" style="float:right">
    <%= paginate @tags %>
  </div>
  <%= link_to "新增", new_tag_path, :class=>"btn btn-primary" %>
  <%= link_to "返回首页", mains_path, :class=>"btn btn-primary" %>
</div>

app/views/tags/new.html.erb
<div class="container">
  <h1>图书标签新增</h1>
  <%= render :partial=>"form" %> 
</div>