config/routes.rb
Rails.application.routes.draw do

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :books do
    collection do
      get :success
    end
  end
  resources :users
  resources :categories
  resources :circulates do
    collection do
      get :tongji
      get :usersTongji
    end
  end
  resources :tags
  resources :sessions
  resources :mains

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: "books#index"

  namespace :interface do
    resources :books, :only =>[] do
      collection do
        get :all
      end
    end
  end

  namespace :interface do
    resources :users, :only =>[] do
      collection do
        get :all
      end
    end
  end
end

app/controllers/mains_controller.rb
class MainsController <ApplicationController

  before_filter :authorize

  def index
     authorize! :read, :message=>"没有权限"
  end
end

app/views/mains/index.html.erb
<style>
  .block{
    float:left;
    background-color:#0696CE;
    width:35%;
    line-height:450%;
    margin-top: 8%;
    margin-right: 15%;
    font-size: 3em;
  }
</style>
<div style="margin-top:2%; margin-left:42%">
  <div id="user_header">
    <% if current_user %>
      欢迎<%= current_user.name %>登陆！
      <%= link_to "退出", logout_path %>
    <% else %>
      <%= link_to "注册", signup_path, :class=>"btn btn-primary" %>
      <%= link_to "登陆", login_path, :class=>"btn btn-primary" %>
    <% end %>
  </div>

</div>
<div class="container" align="center">
  <div class="block"><%= link_to "图书分类管理", categories_path, :style=>"text-decoration:none; color:black" %></div>
  <div class="block"><%= link_to "图书标签管理", tags_path, :style=>"text-decoration:none; color:black" %></div>
  <div class="block"><%= link_to "图书管理", books_path, :style=>"text-decoration:none; color:black" %></div>
  <div class="block"><%= link_to "图书流通状态管理", circulates_path, :style=>"text-decoration:none; color:black" %></div>
</div>