config/routes.rb
Rails.application.routes.draw do

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :books do
    collection do
      get :success
    end
  end
  resources :users
  resources :categories
  resources :circulates do
    collection do
      get :tongji
      get :usersTongji
    end
  end
  resources :tags
  resources :sessions
  resources :mains

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: "books#index"

  namespace :interface do
    resources :books, :only =>[] do
      collection do
        get :all
      end
    end
  end

  namespace :interface do
    resources :users, :only =>[] do
      collection do
        get :all
      end
    end
  end
end

app/models/category.rb
class Category <ActiveRecord::Base
  has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController <ApplicationController

  before_action :find_category_by_id, :only=>[:edit, :destroy, :update]
  before_filter :authorize

  def index
    authorize! :read, :message=>"没有权限"
    @categories = Category.all.page(params[:page]).per(10)
  end

  def new
    authorize! :create, :message=>"没有权限"
    @category = Category.new
  end

  def create
    Category.create :name=>params[:category][:name]
    redirect_to categories_path
  end

  def edit
    authorize! :update, :message=>"没有权限"
  end

  def update
    @category.name = params[:category][:name]
    @category.save
    redirect_to categories_path
  end

  def destroy
    authorize! :destroy, :message=>"没有权限"
    @category.delete
    redirect_to categories_path
  end

  def find_category_by_id
    @category = Category.find(params[:id])
  end

end

app/views/categories/_form.html.erb
<%= form_for @category, :html=>{:id=>"form"} do |f| %>
  <div class="input-group">
    <span class="input-group-addon">请输入分类名称：</span>
    <%= f.text_field :name, :class=>"form-control", :style=>"width:40%" %>
  </div>
  <br/>
  <%= f.submit "确定", :class=>"btn btn-primary" %>
  <%= link_to "返回", categories_path, :class=>"btn btn-primary" %>
<%end%>

app/views/categories/edit.html.erb
<div class="container">
  <h1>图书分类修改</h1>
  <%= render :partial=>"form" %> 
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1>图书分类列表</h1>
  <table class="table table-striped table-hover">
    <tr>
      <th>图书分类名称</th>
      <th>操作</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
	<td>
          <%= link_to "修改", edit_category_path(:id=>category.id), :class=>"btn btn-primary" %>
	  <%= link_to "删除", category_path(:id=>category.id), :class=>"btn btn-danger", :method=>"delete", :data=>{:confirm=>"确定要删除这个分类吗？"} %>
	</td>
      </tr>
    <%end%>
  </table>
  <div class="table-actions-bottom" style="float:right">
    <%= paginate @categories %>
  </div>
  <%= link_to "新增", new_category_path, :class=>"btn btn-primary" %>
  <%= link_to "返回首页", mains_path, :class=>"btn btn-primary" %>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1>图书分类新增</h1>
  <%= render :partial=>"form" %> 
</div>